[[regex.author.names]]
regex = '''
\[([^]]*)\]\(https://www\.goodreads\.com/search\?utf8=%E2%9C%93&q=[^&]*&search_type=books&search%5Bfield%5D=author\)
'''
name_group = 1  # index of regex group that return author name

# to parse old versions you can add additional reqexs like that
# [[author-names]]
