site_name: goodreads-export
site_url: https://andgineer.github.io/goodreads-export
site_author: Andrey Sorokin

# Repository
repo_name: goodreads-export
repo_url: https://github.com/andgineer/goodreads-export
edit_uri: edit/master/docs
docs_dir: docs

plugins:
  - awesome-pages
  - search

theme:
  name: readthedocs
